apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: spark-pi
  namespace: datalake
spec:
  type: Python
  mode: cluster
  image: "minkens/spark-py:latest"
  mainApplicationFile: "local:///opt/spark/examples/src/main/python/pi.py"
  sparkVersion: "3.5.3"
  restartPolicy:
    type: Never
  driver:
    cores: 1
    memory: "512m"
  executor:
    cores: 1
    instances: 1
    memory: "512m"
